export const pokemonsDefault = [
  {
    id: 0,
    image: "image 6.png",
    name: "gfafsg",
    weight: 0.1,
    money: 3,
    moneySum: 4,
    age: 5,
  },
  {
    id: 1,
    image: "image 6.png",
    name: "gfafsg",
    weight: 0.1,
    money: 3,
    moneySum: 4,
    age: 5,
  },
  {
    id: 2,
    image: "image 6.png",
    name: "gfafsg",
    weight: 0.1,
    money: 3,
    moneySum: 4,
    age: 5,
  },
  {
    id: 3,
    image: "image 6.png",
    name: "gfafsg",
    weight: 0.1,
    money: 3,
    moneySum: 4,
    age: 5,
  },
];

export const gardenDefault = [
  {
    id: 0,
    image: "image 5.png",
    name: "Ягода 1 уровня",
    description: "Накорми ей покемона для увеличения веса на 0.1 кг",
    weight: 0.1,
    size: 1,
    cost: 10,
    time: 3600,
  },
  {
    id: 10,
    image: "image 5.png",
    name: "Ягода 1 уровня",
    description: "Накорми ей покемона для увеличения веса на 0.1 кг",
    weight: 0.1,
    size: 1,
    cost: 10,
    time: 3600,
  },
  {
    id: 24,
    image: "image 5.png",
    name: "Ягода 1 уровня",
    description: "Накорми ей покемона для увеличения веса на 0.1 кг",
    weight: 0.1,
    size: 1,
    cost: 10,
    time: 3600,
  },
  {
    id: 30,
    image: "image 5.png",
    name: "Ягода 1 уровня",
    description: "Накорми ей покемона для увеличения веса на 0.1 кг",
    weight: 0.1,
    size: 1,
    cost: 10,
    time: 3600,
  },
];
